name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm 
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install dependencies
      run: |
          cd react-redux-realworld-example-app && npm ci
          cd ../node-express-realworld-example-app && npm ci
    - name: Unit Test API
      run: 
          cd node-express-realworld-example-app && npm run test
    - name: Run backend
      run: |
          cd node-express-realworld-example-app 
          docker-compose up -d
          npm run
    - name: Run frontend
      run: |
          cd react-redux-realworld-example-app
          docker ps 
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        start: |
         npm start
        working-directory: react-redux-realworld-example-app
